channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  - pillow=12.2.0
  - matplotlib=3.10.9
  - numpy=2.4.3
  - cartopy=0.24.1
  - pip==26.1.1
  - pip:
    - timm==1.0.26
    - open-clip-torch==3.3.0
    - grad-cam==1.5.5
